<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitce53c0a1b19ddaa6a69c1d2ee52399ff
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitce53c0a1b19ddaa6a69c1d2ee52399ff::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitce53c0a1b19ddaa6a69c1d2ee52399ff::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitce53c0a1b19ddaa6a69c1d2ee52399ff::$classMap;

        }, null, ClassLoader::class);
    }
}
